config/routes.rb
Rails3MongoidOmniauth::Application.routes.draw do
  resources :matches

  resources :books

  resources :wants

  resources :haves

  match '/update-number' => "home#update", :as => :update_number
  

  root :to => "home#index"

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/models/want.rb
class Want
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  has_one :book
  accepts_nested_attributes_for :book, :allow_destroy => true
  
  def to_s
    if self.book
        self.book
    end
  end
  
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  # GET /wants
  # GET /wants.json
  def index
    @wants = Want.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wants }
    end
  end

  # GET /wants/1
  # GET /wants/1.json
  def show
    @want = Want.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @want }
    end
  end

  # GET /wants/new
  # GET /wants/new.json
  def new
    @want = Want.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @want }
    end
  end

  # GET /wants/1/edit
  def edit
    @want = Want.find(params[:id])
  end

  # POST /wants
  # POST /wants.json
  def create
    @want = current_user.wants.create!
    @book = Book.create(:title => params[:title], :version => params[:version])
    @want.book = @book
    @want.save!
    @wants = current_user.wants.all
    respond_to do |format|
      if @want.save
        format.html { redirect_to @want, notice: 'Want was successfully created.' }
       # format.json { render json: @want, status: :created, location: @want }
       format.js 
      else
        format.html { render action: "new" }
        format.json { render json: @want.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wants/1
  # PUT /wants/1.json
  def update
    @want = Want.find(params[:id])

    respond_to do |format|
      if @want.update_attributes(params[:want])
        format.html { redirect_to @want, notice: 'Want was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @want.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wants/1
  # DELETE /wants/1.json
  def destroy
    @want = Want.find(params[:id])
    @want.destroy

    respond_to do |format|
      format.html { redirect_to wants_url }
      format.json { head :ok }
    end
  end
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/wants/_form.html.erb
<%= form_for(@want) do |f| %>
  <% if @want.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@want.errors.count, "error") %> prohibited this want from being saved:</h2>

      <ul>
      <% @want.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	Title:<br/><input name="[title]">
  </div>

  <div class="field">
    Version:<br/><input name="[version]">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wants/create.js.erb
$('#wants').html('<% @wants.each do |have| %><p><%= have %></p><% end %>');

app/views/wants/edit.html.erb
<h1>Editing want</h1>

<%= render 'form' %>

<%= link_to 'Show', @want %> |
<%= link_to 'Back', wants_path %>

app/views/wants/index.html.erb
<h1>Listing wants</h1>

<table>
  <tr>
    <th>Book</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wants.each do |want| %>
  <tr>
    <td><%= want.book %></td>
    <td><%= want.user %></td>
    <td><%= link_to 'Show', want %></td>
    <td><%= link_to 'Edit', edit_want_path(want) %></td>
    <td><%= link_to 'Destroy', want, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Want', new_want_path %>

app/views/wants/new.html.erb
<h1>New want</h1>

<%= render 'form' %>

<%= link_to 'Back', wants_path %>

app/views/wants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @want.book.title %>
</p>

<%= link_to 'Edit', edit_want_path(@want) %> |
<%= link_to 'Back', wants_path %>