config/routes.rb
Rails3MongoidOmniauth::Application.routes.draw do
  resources :matches

  resources :books

  resources :wants

  resources :haves

  match '/update-number' => "home#update", :as => :update_number
  

  root :to => "home#index"

  resources :users, :only => [ :show, :edit, :update ]

  match '/auth/:provider/callback' => 'sessions#create'

  match '/signin' => 'sessions#new', :as => :signin

  match '/signout' => 'sessions#destroy', :as => :signout

  match '/auth/failure' => 'sessions#failure'

end

app/models/have.rb
class Have
  include Mongoid::Document
  include Mongoid::Timestamps

  has_one :book
  belongs_to :user
  accepts_nested_attributes_for :book, :allow_destroy => true
  
  def to_s
    if self.book
      self.book.title
    end
  end
  
end

app/controllers/haves_controller.rb
class HavesController < ApplicationController
  # GET /haves
  # GET /haves.json
  def index
    @haves = Have.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @haves }
    end
  end

  # GET /haves/1
  # GET /haves/1.json
  def show
    @have = Have.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @have }
    end
  end

  # GET /haves/new
  # GET /haves/new.json
  def new
    @have = Have.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @have }
    end
  end

  # GET /haves/1/edit
  def edit
    @have = Have.find(params[:id])
  end

  # POST /haves
  # POST /haves.json
  def create

     @have = current_user.haves.create!
      @book = Book.create!(:title => params[:title], :version => params[:version])
      @have.book = @book
      @have.save!
    @haves = current_user.haves.all
    respond_to do |format|
      if @have.save
        format.html { redirect_to @have, notice: 'Have was successfully created.' }
       # format.json { render json: @have, status: :created, location: @have }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @have.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /haves/1
  # PUT /haves/1.json
  def update
    @have = Have.find(params[:id])
    respond_to do |format|
      if @have.update_attributes(params[:hafe])
        format.html { redirect_to @have, notice: 'Have was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @have.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /haves/1
  # DELETE /haves/1.json
  def destroy
    @have = Have.find(params[:id])
    @have.destroy

    respond_to do |format|
      format.html { redirect_to haves_url }
      format.json { head :ok }
    end
  end
end

app/helpers/haves_helper.rb
module HavesHelper
end

app/views/haves/_form.html.erb
<%= form_for(@have) do |f| %>
  <% if @have.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@have.errors.count, "error") %> prohibited this hafe from being saved:</h2>

      <ul>
      <% @have.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
	Title:<br/><input name="[title]">
  </div>

  <div class="field">
    Version:<br/><input name="[version]">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/haves/create.js.erb
$('#haves').html('<% @haves.each do |have| %><p><%= have %></p><% end %>');

app/views/haves/edit.html.erb
<h1>Editing hafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @hafe %> |
<%= link_to 'Back', haves_path %>

app/views/haves/index.html.erb
<h1>Listing haves</h1>

<table>
  <tr>
    <th>Book</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @haves.each do |have| %>

  <tr>
	
    <td><%= have.book.title %></td>
    <td><%= have.book.version %></td>

    <td><%= link_to 'Show', have %></td>
    <td><%= link_to 'Edit', edit_have_path(have) %></td>
    <td><%= link_to 'Destroy', have, confirm: 'Are you sure?', method: :delete %></td>
  </tr>




<% end %>
</table>

<br />

<%= link_to 'New Have', new_have_path %>

app/views/haves/new.html.erb
<h1>New have</h1>

<%= render 'form' %>

<%= link_to 'Back', haves_path %>

app/views/haves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book:</b>
  <%= @have.book.title %>
</p>


<%= link_to 'Edit', edit_have_path(@have) %> |
<%= link_to 'Back', haves_path %>